# [unstable]
# build-std-features = ["compiler-builtins-mem"]
# build-std = ["core", "compiler_builtins"]
#  
# [build]
# target = "atomkern_os.json"

# [target.'cfg(target_os = "none")']
# runner = "cargo run --package simple_boot --"

# [alias]
# kbuild = "build --target atomkern_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
# kimage = "run --target atomkern_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --no-run"
# krun = "run --target atomkern_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"

[unstable]
bindeps = true
# build-std-features = ["compiler-builtins-mem"]
# build-std = ["core", "compiler_builtins"]
